In [89]:
import pandas as pd

In [90]:
df=pd.read_csv('Auto_Sales_data.csv')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,DAYS_SINCE_LASTORDER,STATUS,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,24/02/2018,828,Shipped,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,07/05/2018,757,Shipped,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,01/07/2018,703,Shipped,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,25/08/2018,649,Shipped,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10168,36,96.66,1,3479.76,28/10/2018,586,Shipped,Motorcycles,95,S10_1678,Technics Stores Inc.,6505556809,9408 Furth Circle,Burlingame,94217,USA,Hirano,Juri,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2742,10350,20,112.22,15,2244.40,02/12/2019,2924,Shipped,Ships,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2743,10373,29,137.19,1,3978.51,31/01/2020,2865,Shipped,Ships,54,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2744,10386,43,125.99,4,5417.57,01/03/2020,2836,Resolved,Ships,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2745,10397,34,62.24,1,2116.16,28/03/2020,2810,Shipped,Ships,54,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2746,10414,47,65.52,9,3079.44,06/05/2020,2772,On Hold,Ships,54,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

# Filtering rows based on quantity

In [91]:
df = df[df['QUANTITYORDERED']>20]
df =  df[df['DEALSIZE'] == 'Medium']
df.shape

(1334, 20)

# Feature selection based on importance

In [92]:
features = ['ORDERNUMBER','QUANTITYORDERED','PRICEEACH','SALES','ORDERDATE','PRODUCTCODE','COUNTRY','DEALSIZE']
# df = df[features]
df.shape

(1334, 20)

In [60]:
df.groupby('COUNTRY')['DEALSIZE'].count()

COUNTRY
Australia       86
Austria         29
Belgium         15
Canada          33
Denmark         30
Finland         46
France         147
Germany         30
Ireland          6
Italy           43
Japan           21
Norway          42
Philippines     14
Singapore       37
Spain          169
Sweden          31
Switzerland     22
UK              69
USA            464
Name: DEALSIZE, dtype: int64

In [61]:
df.groupby('COUNTRY')['SALES'].sum()

COUNTRY
Australia       381245.00
Austria         125314.10
Belgium          71531.37
Canada          137430.48
Denmark         136581.50
Finland         201741.96
France          636914.22
Germany         133151.79
Ireland          26822.87
Italy           180466.28
Japan           101097.22
Norway          190502.23
Philippines      62415.84
Singapore       175371.74
Spain           749092.69
Sweden          143685.97
Switzerland      98617.40
UK              294225.02
USA            2029196.19
Name: SALES, dtype: float64

In [62]:
df.groupby('COUNTRY')['QUANTITYORDERED'].mean()

COUNTRY
Australia      36.988372
Austria        39.000000
Belgium        40.866667
Canada         36.333333
Denmark        37.466667
Finland        37.239130
France         38.775510
Germany        36.300000
Ireland        33.000000
Italy          36.651163
Japan          40.714286
Norway         36.714286
Philippines    39.571429
Singapore      37.351351
Spain          39.230769
Sweden         40.225806
Switzerland    36.772727
UK             38.362319
USA            38.187500
Name: QUANTITYORDERED, dtype: float64

In [63]:
oldest_date,latest_date = df['ORDERDATE'].min(),df['ORDERDATE'].max()
oldest_date,latest_date

('01/03/2020', '31/05/2020')

In [64]:
df.groupby('COUNTRY').agg({'SALES':['count','sum','mean']})

            SALES
            count         sum         mean
COUNTRY
Australia      86   381245.00  4433.081395
Austria        29   125314.10  4321.175862
Belgium        15    71531.37  4768.758000
Canada         33   137430.48  4164.560000
Denmark        30   136581.50  4552.716667
Finland        46   201741.96  4385.694783
France        147   636914.22  4332.749796
Germany        30   133151.79  4438.393000
Ireland         6    26822.87  4470.478333
Italy          43   180466.28  4196.890233
Japan          21   101097.22  4814.153333
Norway         42   190502.23  4535.767381
Philippines    14    62415.84  4458.274286
Singapore      37   175371.74  4739.776757
Spain         169   749092.69  4432.501124
Sweden         31   143685.97  4635.031290
Switzerland    22    98617.40  4482.609091
UK             69   294225.02  4264.130725
USA           464  2029196.19  4373.267651

In [65]:
df_feature = df[features]
df_feature

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,COUNTRY,DEALSIZE
2,10134,41,94.74,3884.34,01/07/2018,S10_1678,France,Medium
3,10145,45,83.26,3746.70,25/08/2018,S10_1678,USA,Medium
4,10168,36,96.66,3479.76,28/10/2018,S10_1678,USA,Medium
6,10188,48,114.84,5512.32,18/11/2018,S10_1678,Norway,Medium
7,10211,41,114.84,4708.44,15/01/2019,S10_1678,France,Medium
...,...,...,...,...,...,...,...,...
2740,10327,37,86.74,3209.38,10/11/2019,S72_3212,Denmark,Medium
2741,10337,42,97.16,4080.72,21/11/2019,S72_3212,USA,Medium
2743,10373,29,137.19,3978.51,31/01/2020,S72_3212,Finland,Medium
2744,10386,43,125.99,5417.57,01/03/2020,S72_3212,Spain,Medium
2746,10414,47,65.52,3079.44,06/05/2020,S72_3212,USA,Medium

In [66]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,DAYS_SINCE_LASTORDER,STATUS,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2,10134,41,94.74,2,3884.34,01/07/2018,703,Shipped,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,25/08/2018,649,Shipped,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10168,36,96.66,1,3479.76,28/10/2018,586,Shipped,Motorcycles,95,S10_1678,Technics Stores Inc.,6505556809,9408 Furth Circle,Burlingame,94217,USA,Hirano,Juri,Medium
6,10188,48,114.84,1,5512.32,18/11/2018,567,Shipped,Motorcycles,95,S10_1678,Herkku Gifts,+47 2267 3215,"Drammen 121, PR 744 Sentrum",Bergen,N 5804,Norway,Oeztan,Veysel,Medium
7,10211,41,114.84,14,4708.44,15/01/2019,510,Shipped,Motorcycles,95,S10_1678,Auto Canal Petit,(1) 47.55.6555,"25, rue Lauriston",Paris,75016,France,Perrier,Dominique,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2740,10327,37,86.74,4,3209.38,10/11/2019,2944,Resolved,Ships,54,S72_3212,Danish Wholesale Imports,31 12 3555,Vinb'ltet 34,Kobenhavn,1734,Denmark,Petersen,Jytte,Medium
2741,10337,42,97.16,5,4080.72,21/11/2019,2934,Shipped,Ships,54,S72_3212,Classic Legends Inc.,2125558493,5905 Pompton St.,NYC,10022,USA,Hernandez,Maria,Medium
2743,10373,29,137.19,1,3978.51,31/01/2020,2865,Shipped,Ships,54,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2744,10386,43,125.99,4,5417.57,01/03/2020,2836,Resolved,Ships,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2746,10414,47,65.52,9,3079.44,06/05/2020,2772,On Hold,Ships,54,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [67]:
df = df[['PRODUCTLINE','STATUS','MSRP','CITY','COUNTRY']]

# Inner Merge

In [68]:
pd.merge(df,df_feature,on='COUNTRY')

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,DEALSIZE
0,Motorcycles,Shipped,95,Paris,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
1,Motorcycles,Shipped,95,Paris,France,10211,41,114.84,4708.44,15/01/2019,S10_1678,Medium
2,Motorcycles,Shipped,95,Paris,France,10275,45,92.83,4177.35,23/07/2019,S10_1678,Medium
3,Motorcycles,Shipped,95,Paris,France,10134,27,122.51,3307.77,01/07/2018,S10_2016,Medium
4,Motorcycles,Shipped,95,Paris,France,10180,42,111.80,4695.60,11/11/2018,S10_2016,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
290789,Ships,On Hold,54,Boston,USA,10168,39,82.91,3233.49,28/10/2018,S700_4002,Medium
290790,Ships,On Hold,54,Boston,USA,10222,43,74.03,3183.29,19/02/2019,S700_4002,Medium
290791,Ships,On Hold,54,Boston,USA,10329,44,86.13,3789.72,15/11/2019,S72_1253,Medium
290792,Ships,On Hold,54,Boston,USA,10337,42,97.16,4080.72,21/11/2019,S72_3212,Medium
290793,Ships,On Hold,54,Boston,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium

# Left Merge

In [73]:
new_row = pd.DataFrame({'COUNTRY':['INDIA']})
df = pd.concat([df,new_row])
df

      PRODUCTLINE    STATUS  MSRP        CITY  COUNTRY
2     Motorcycles   Shipped  95.0       Paris   France
3     Motorcycles   Shipped  95.0    Pasadena      USA
4     Motorcycles   Shipped  95.0  Burlingame      USA
6     Motorcycles   Shipped  95.0      Bergen   Norway
7     Motorcycles   Shipped  95.0       Paris   France
...           ...       ...   ...         ...      ...
2741        Ships   Shipped  54.0         NYC      USA
2743        Ships   Shipped  54.0        Oulu  Finland
2744        Ships  Resolved  54.0      Madrid    Spain
2746        Ships   On Hold  54.0      Boston      USA
0             NaN       NaN   NaN         NaN    INDIA

[1335 rows x 5 columns]

In [74]:
pd.merge(df,df_feature,how='left',on='COUNTRY')

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,DEALSIZE
0,Motorcycles,Shipped,95.0,Paris,France,10134.0,41.0,94.74,3884.34,01/07/2018,S10_1678,Medium
1,Motorcycles,Shipped,95.0,Paris,France,10211.0,41.0,114.84,4708.44,15/01/2019,S10_1678,Medium
2,Motorcycles,Shipped,95.0,Paris,France,10275.0,45.0,92.83,4177.35,23/07/2019,S10_1678,Medium
3,Motorcycles,Shipped,95.0,Paris,France,10134.0,27.0,122.51,3307.77,01/07/2018,S10_2016,Medium
4,Motorcycles,Shipped,95.0,Paris,France,10180.0,42.0,111.80,4695.60,11/11/2018,S10_2016,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
290790,Ships,On Hold,54.0,Boston,USA,10222.0,43.0,74.03,3183.29,19/02/2019,S700_4002,Medium
290791,Ships,On Hold,54.0,Boston,USA,10329.0,44.0,86.13,3789.72,15/11/2019,S72_1253,Medium
290792,Ships,On Hold,54.0,Boston,USA,10337.0,42.0,97.16,4080.72,21/11/2019,S72_3212,Medium
290793,Ships,On Hold,54.0,Boston,USA,10414.0,47.0,65.52,3079.44,06/05/2020,S72_3212,Medium
290794,NaN,NaN,NaN,NaN,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Right Merge

In [75]:
pd.merge(df,df_feature,how='right',on='COUNTRY')

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,DEALSIZE
0,Motorcycles,Shipped,95.0,Paris,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
1,Motorcycles,Shipped,95.0,Paris,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
2,Motorcycles,Shipped,95.0,Nantes,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
3,Motorcycles,Shipped,118.0,Paris,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
4,Motorcycles,Shipped,118.0,Lille,France,10134,41,94.74,3884.34,01/07/2018,S10_1678,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
290789,Planes,Shipped,74.0,Burlingame,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium
290790,Planes,Shipped,74.0,San Diego,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium
290791,Planes,Shipped,49.0,NYC,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium
290792,Ships,Shipped,54.0,NYC,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium
290793,Ships,On Hold,54.0,Boston,USA,10414,47,65.52,3079.44,06/05/2020,S72_3212,Medium

# Outer Merge

In [82]:
pd.merge(df,df_feature,how='outer',on='COUNTRY')

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,DEALSIZE
0,Motorcycles,Shipped,95.0,Melbourne,Australia,10223.0,37.0,107.18,3965.66,20/02/2019,S10_1678,Medium
1,Motorcycles,Shipped,95.0,Melbourne,Australia,10270.0,21.0,233.59,4905.39,19/07/2019,S10_1949,Medium
2,Motorcycles,Shipped,95.0,Melbourne,Australia,10347.0,30.0,131.49,3944.70,29/11/2019,S10_1949,Medium
3,Motorcycles,Shipped,95.0,Melbourne,Australia,10223.0,47.0,115.37,5422.39,20/02/2019,S10_2016,Medium
4,Motorcycles,Shipped,95.0,Melbourne,Australia,10374.0,39.0,135.59,5288.01,02/02/2020,S10_2016,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
290790,Ships,On Hold,54.0,Boston,USA,10168.0,39.0,82.91,3233.49,28/10/2018,S700_4002,Medium
290791,Ships,On Hold,54.0,Boston,USA,10222.0,43.0,74.03,3183.29,19/02/2019,S700_4002,Medium
290792,Ships,On Hold,54.0,Boston,USA,10329.0,44.0,86.13,3789.72,15/11/2019,S72_1253,Medium
290793,Ships,On Hold,54.0,Boston,USA,10337.0,42.0,97.16,4080.72,21/11/2019,S72_3212,Medium
290794,Ships,On Hold,54.0,Boston,USA,10414.0,47.0,65.52,3079.44,06/05/2020,S72_3212,Medium

# JOINING DFs

In [86]:
df.join(df_feature, lsuffix='_left', rsuffix='_right')

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY_left,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,COUNTRY_right,DEALSIZE
2,Motorcycles,Shipped,95.0,Paris,France,10134.0,41.0,94.74,3884.34,01/07/2018,S10_1678,France,Medium
3,Motorcycles,Shipped,95.0,Pasadena,USA,10145.0,45.0,83.26,3746.70,25/08/2018,S10_1678,USA,Medium
4,Motorcycles,Shipped,95.0,Burlingame,USA,10168.0,36.0,96.66,3479.76,28/10/2018,S10_1678,USA,Medium
6,Motorcycles,Shipped,95.0,Bergen,Norway,10188.0,48.0,114.84,5512.32,18/11/2018,S10_1678,Norway,Medium
7,Motorcycles,Shipped,95.0,Paris,France,10211.0,41.0,114.84,4708.44,15/01/2019,S10_1678,France,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,Ships,Shipped,54.0,NYC,USA,10337.0,42.0,97.16,4080.72,21/11/2019,S72_3212,USA,Medium
2743,Ships,Shipped,54.0,Oulu,Finland,10373.0,29.0,137.19,3978.51,31/01/2020,S72_3212,Finland,Medium
2744,Ships,Resolved,54.0,Madrid,Spain,10386.0,43.0,125.99,5417.57,01/03/2020,S72_3212,Spain,Medium
2746,Ships,On Hold,54.0,Boston,USA,10414.0,47.0,65.52,3079.44,06/05/2020,S72_3212,USA,Medium
0,NaN,NaN,NaN,NaN,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# CONCAT DFs

In [87]:
pd.concat([df,df_feature])

,PRODUCTLINE,STATUS,MSRP,CITY,COUNTRY,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,PRODUCTCODE,DEALSIZE
2,Motorcycles,Shipped,95.0,Paris,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Motorcycles,Shipped,95.0,Pasadena,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Motorcycles,Shipped,95.0,Burlingame,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Motorcycles,Shipped,95.0,Bergen,Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Motorcycles,Shipped,95.0,Paris,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2740,NaN,NaN,NaN,NaN,Denmark,10327.0,37.0,86.74,3209.38,10/11/2019,S72_3212,Medium
2741,NaN,NaN,NaN,NaN,USA,10337.0,42.0,97.16,4080.72,21/11/2019,S72_3212,Medium
2743,NaN,NaN,NaN,NaN,Finland,10373.0,29.0,137.19,3978.51,31/01/2020,S72_3212,Medium
2744,NaN,NaN,NaN,NaN,Spain,10386.0,43.0,125.99,5417.57,01/03/2020,S72_3212,Medium
2746,NaN,NaN,NaN,NaN,USA,10414.0,47.0,65.52,3079.44,06/05/2020,S72_3212,Medium

# Pivot table

In [94]:
pivot = pd.pivot_table(df,index='COUNTRY',columns='PRODUCTLINE',values='SALES',aggfunc='mean')
pivot

PRODUCTLINE,Classic Cars,Motorcycles,Planes,Ships,Trains,Trucks and Buses,Vintage Cars
COUNTRY,,,,,,,
Australia,4555.124643,4285.091111,3936.615000,3070.400000,NaN,4751.434545,4502.405200
Austria,4259.513333,3994.780000,5280.120000,NaN,NaN,5048.576667,3736.832500
Belgium,5034.240000,NaN,5624.790000,4528.223333,5450.590000,NaN,4455.726667
Canada,4531.479000,4177.490000,3309.050000,3849.960000,NaN,4528.920000,3777.990000
Denmark,5103.000000,NaN,4781.700000,3871.924000,4330.100000,4794.410000,3374.652000
Finland,4516.422105,4913.517143,4354.440000,3877.950000,3128.650000,4559.384286,3227.823333
France,4362.861667,4400.387241,4207.241333,3866.130000,4957.890000,4656.872727,4094.130000
Germany,4587.812000,3127.820000,4681.526667,3477.860000,NaN,5089.000000,3522.430000
Ireland,4930.520000,NaN,4024.130000,NaN,NaN,3983.050000,NaN
Italy,5070.064286,4764.600000,3930.591875,3584.973333,NaN,3114.890000,4230.130000
Japan,5426.555000,4269.450000,5034.837500,4010.895000,NaN,6060.620000,3712.685000
Norway,4697.283000,4352.860000,4760.616667,NaN,5655.180000,3863.077143,4484.266667
Philippines,4731.288000,3536.520000,4014.960000,NaN,NaN,NaN,NaN
Singapore,4970.993077,4175.600000,NaN,3990.506667,5344.500000,4781.486000,4383.730000
Spain,4850.548361,4280.199000,3861.071875,4223.212941,4169.675714,4532.591250,4084.281176
Sweden,4507.568889,5189.083333,5763.720000,3496.108333,3807.680000,5695.547143,4283.430000
Switzerland,4482.609091,NaN,NaN,NaN,NaN,NaN,NaN
UK,4449.525000,5238.550000,4299.952500,4106.937273,4134.400000,4430.352500,3933.049444
USA,4518.219231,4294.280758,4188.658000,3849.692143,4018.901250,4701.706140,4236.546354