In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'City': ['New York', 'London', 'New York', 'Tokyo', 'London'],
    'Education': ['Bachelors', 'PhD', 'Masters', 'Bachelors', 'Masters'],
    'Salary': [70000, 120000, 95000, 65000, 100000]
}
df = pd.DataFrame(data)

In [4]:
df

       City  Education  Salary
0  New York  Bachelors   70000
1    London        PhD  120000
2  New York    Masters   95000
3     Tokyo  Bachelors   65000
4    London    Masters  100000

In [18]:
targeted_encoding = df.groupby('City')['Salary'].mean()
df['City_target'] = df['City'].map(targeted_encoding)
# df.drop(columns={'City_targeted'},inplace=True)
df

       City  Education  Salary  City_target
0  New York  Bachelors   70000      82500.0
1    London        PhD  120000     110000.0
2  New York    Masters   95000      82500.0
3     Tokyo  Bachelors   65000      65000.0
4    London    Masters  100000     110000.0

In [19]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder,TargetEncoder

# Labelencoding :-
le = LabelEncoder()
df['City_label'] = le.fit_transform(df['City'])
df

       City  Education  Salary  City_target  City_label
0  New York  Bachelors   70000      82500.0           1
1    London        PhD  120000     110000.0           0
2  New York    Masters   95000      82500.0           1
3     Tokyo  Bachelors   65000      65000.0           2
4    London    Masters  100000     110000.0           0

In [34]:
# OneHotEncoding
ohe = OneHotEncoder(sparse_output=False,drop='first')
encoder_data = ohe.fit_transform(df[['Education']])

In [35]:
encoder_data

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [33]:
# TargetEncoding
te = TargetEncoder(target_type='continuous',cv=2,random_state=42)
df['City_targeted'] = te.fit_transform(X = df[['City']],y = df['Salary'])
df

       City  Education  Salary  City_target  City_label  City_targeted
0  New York  Bachelors   70000      82500.0           1        95000.0
1    London        PhD  120000     110000.0           0        67500.0
2  New York    Masters   95000      82500.0           1        70000.0
3     Tokyo  Bachelors   65000      65000.0           2       105000.0
4    London    Masters  100000     110000.0           0        67500.0